spring.application.name=emissions-calculator-beta

# Conexao PostgreSQL/PostGIS
spring.datasource.url=jdbc:postgresql://localhost:5432/spire_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true